### ISSUE TITLE
Plugin pushing data only for First Thread Group, rest of Thread Group data is not pushed.

### ISSUE THREAD

**Issue by tavish9** [adrianmo/jmeter-backend-azure#7] opened 2020-05-02 12:50 UTC
I have multiple 'Thread Group'(s) in my Test Plan. But the plugin is pushing data to AppInsights only for first Thread Group.

![image](https://user-images.githubusercontent.com/64127305/80864645-a25f4f80-8ca1-11ea-9e0f-be8fd094595f.png)

**Comment by adrianmo** [comment] 2020-05-04 07:25
Hi @tavish9, thank you for using the plugin and for reporting the issue. I will try to reproduce the bug and get back to you when I find something or if I need more information.

**Comment by adrianmo** [comment] 2020-05-07 09:46
@tavish9 FYI I was able to reproduce the issue - I'll get back to you when it's fixed.

**Comment by adrianmo** [comment] 2020-05-07 15:07
@tavish9 it looks like having two or more backend listeners with the same name causes problems. Can you please try to rename them so that they don't have same name? e.g. `Backend Listener 1` and `Backend Listener 2`.

**Comment by adrianmo** [comment] 2020-05-08 09:11
FYI - I've also released a new version (i.e. 0.2.2) that adds the ability to filter samplers using a list (separated by semi-colon) or using regex. Please have a look at the updated README.

I'm closing this issue, but feel free to reopen it if you keep experiencing problems.

**Closed by adrianmo** 2020-05-08 09:11 UTC
Labels: bug
